using System.Diagnostics;

// Problem2
//
// Even Fibonacci numbers
//
// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

namespace Problem2;

internal class Program
{
    private static void Main()
    {
        const int upperBound = 4_000_000;
        var timeTaken = new Stopwatch();
        timeTaken.Start();

        var priorFibonacci = 0;
        var currentFibonacci = 1;
        var sum = 0;

        while (true)
        {
            var nextFibonacci = priorFibonacci + currentFibonacci;
            Console.WriteLine($"prior {priorFibonacci}, fib {currentFibonacci}, next {nextFibonacci}");

            if (nextFibonacci > upperBound) break;

            if (nextFibonacci % 2 == 0) sum += nextFibonacci;

            priorFibonacci = currentFibonacci;
            currentFibonacci = nextFibonacci;
        }

        timeTaken.Stop();
        Console.WriteLine(
            $"The sum of the even valued terms is {sum} with a fibonacci number less that {upperBound}, taking {timeTaken.ElapsedMilliseconds} ms.");
    }
}